CREATE DATABASE IF NOT EXISTS `noomnim_chat` CHARACTER SET utf8mb4 COLLATE=utf8mb4_unicode_ci;
USE `noomnim_chat`;

CREATE TABLE `client` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE `group` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE `message` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `content` TEXT NOT NULL,
    `posted_by` INT UNSIGNED NOT NULL,
    `group_id` INT UNSIGNED NOT NULL,
    FOREIGN KEY (`posted_by`) REFERENCES `client`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`group_id`) REFERENCES `group`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `member` (
    `client_id` INT UNSIGNED NOT NULL,
    `group_id` INT UNSIGNED NOT NULL,
    `last_msg_id` INT UNSIGNED NOT NULL,
    CONSTRAINT `pk_clientGroup` PRIMARY KEY (`client_id`, `group_id`),
    FOREIGN KEY (`client_id`) REFERENCES `client`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`group_id`) REFERENCES `group`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`last_msg_id`) REFERENCES `message`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
