version: '3'

services:
  gateway:
    build: gateway
    ports:
    - 8080:8080
    links:
    - backend
    - group
    links:
    - backend
    - group

  backend:
    build: backend
    ports:
    - 3000:3000
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      REDIS_HOST: redis
    links:
    - db
    - redis

  group:
    build: group
    ports:
    - 3010:3010
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
    links:
    - db

  frontend:
    build: ../noomnim-chat-frontend
    ports:
    - 80:80

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
    - 8888:80
    links:
    - db

  redis:
    image: redis
