http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  group:
    paths: '/api/group/*'
  back:
    paths: '/api/*'
  front:
    paths: '*'
serviceEndpoints:
  backend:
    url: 'http://localhost:3000'
  group-service:
    url: 'http://localhost:3010'
  frontend:
    url: 'http://localhost:4200'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  groupApi:
    apiEndpoints:
      - group
    policies:
      - proxy:
          - action:
              serviceEndpoint: group-service
              prependPath: true
              ignorePath: false
              stripPath: true
  backApi:
    apiEndpoints:
      - back
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: backend
              prependPath: true
              ignorePath: false
              stripPath: true
              ws: true
  frontApi:
    apiEndpoints:
      - front
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: frontend
