http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  back:
    host: localhost
    paths: '/api/*'
  front:
    host: localhost
serviceEndpoints:
  backend:
    url: 'http://localhost:3000'
  frontend: 
    url: 'http://localhost:4200'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  backApi:
    apiEndpoints:
      - back
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action: 
              serviceEndpoint: backend
              prependPath: true
              ignorePath: false
              stripPath: true
  frontApi:
    apiEndpoints:
      - front
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action: 
              serviceEndpoint: frontend